### ISSUE TITLE
x-ui命令报错

### ISSUE THREAD

**Issue by tao-shen** [yonggekkk/x-ui-yg#6]
(base) ➜  ~ x-ui                                                                        
/usr/bin/x-ui: 12: eval: [[: not found
/usr/bin/x-ui: 13: eval: [[: not found
/usr/bin/x-ui: 302: eval: Syntax error: "(" unexpected

已测试多台服务器。系统是ubuntu 18.04和20.04。

另外请问能否加入手动重选一次warp ip的功能 \doge

**Comment by tao-shen** [comment]
另外能不能优化一下显示，比如显示当前warp获得的ip。

**Comment by us254** [comment]
The error seems to be related to the shell script that runs the x-ui command. [It might be caused by using an incompatible shell such as dash instead of bash](https://github.com/vaxilu/x-ui)[3](https://github.com/vaxilu/x-ui). [A possible solution is to change the default shell to bash or run the command with bash explicitly](https://github.com/NidukaAkalanka/x-ui-english)[4](https://github.com/NidukaAkalanka/x-ui-english).

**Comment by yonggekkk** [comment]
> (base) ➜ ~ x-ui /usr/bin/x-ui: 12: eval: [[: not found /usr/bin/x-ui: 13: eval: [[: not found /usr/bin/x-ui: 302: eval: Syntax error: "(" unexpected
> 
> 已测试多台服务器。系统是ubuntu 18.04和20.04。
> 
> 另外请问能否加入手动重选一次warp ip的功能 \doge

我试了没问题。。。你是什么VPS？方便的进TG群，私下我

**Comment by yonggekkk** [comment]
> 另外能不能优化一下显示，比如显示当前warp获得的ip。

带warp显示会拖慢脚本，之前有显示，现在移除了，我到时优化下XUI进入warp的选项吧

**Comment by 14790897** [comment]
甬哥怎么赚钱的？出期视频讲讲

**Comment by yonggekkk** [comment]
> 甬哥怎么赚钱的？出期视频讲讲

下回油管直播你直接提问吧。哈哈
